Change desktopintegration to use universal dialog tool

diff --git a/resources/desktopintegration b/resources/desktopintegration
--- a/resources/desktopintegration
+++ b/resources/desktopintegration
@@ -1,5 +1,25 @@
 #!/bin/bash
 
+# Copyright (c) 2004-2017 Simon Peter
+#
+# Permission is hereby granted, free of charge, to any person obtaining a copy
+# of this software and associated documentation files (the "Software"), to deal
+# in the Software without restriction, including without limitation the rights
+# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
+# copies of the Software, and to permit persons to whom the Software is
+# furnished to do so, subject to the following conditions:
+#
+# The above copyright notice and this permission notice shall be included in all
+# copies or substantial portions of the Software.
+#
+# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
+# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
+# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
+# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
+# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
+# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
+# SOFTWARE.
+
 # The purpose of this script is to provide lightweight desktop integration
 # into the host system without special help from the host system.
 # If you want to use it, then place this in usr/bin/$APPNAME.wrapper
@@ -44,10 +64,6 @@ NUMBER_OF_ARGS="$#"
 # such as desktop integration daemons
 VENDORPREFIX=appimagekit
 
-log () {
-  echo "$@" 1>&2
-}
-
 find-up () {
   path="$(dirname "$(readlink -f "${THIS}")")"
   while [[ "$path" != "" && ! -e "$path/$1" ]]; do
@@ -80,13 +96,13 @@ fi
 RETURN="yes"
 
 if [[ "$FILENAME" != *.wrapper ]] ; then
-  log "${THIS} is not named correctly. It should be named \$Exec.wrapper"
+  echo "${THIS} is not named correctly. It should be named \$Exec.wrapper"
   exit 0
 fi
 
 BIN=$(echo "$FILENAME" | sed -e 's|.wrapper||g')
 if [[ ! -f "$BIN" ]] ; then
-  log "$BIN not found"
+  echo "$BIN not found"
   exit 0
 fi
 
@@ -107,44 +123,6 @@ atexit()
   fi
 }
 
-error()
-{
-  if type yad >/dev/null 2>&1; then
-    LD_LIBRARY_PATH="" yad --borders=15 --center --on-top --width=400 --height=250 --error --button=gtk-ok: 0--text="${1}" 2>/dev/null
-  elif type zenity >/dev/null 2>&1; then
-    LD_LIBRARY_PATH="" zenity --error --text="${1}" 2>/dev/null
-  elif type kdialog >/dev/null 2>&1; then
-    LD_LIBRARY_PATH="" kdialog --error "${1}" 2>/dev/null
-  elif type Xdialog >/dev/null 2>&1; then
-    LD_LIBRARY_PATH="" Xdialog --msgbox "${1}" 2>/dev/null
-  elif type xmessage >/dev/null 2>&1; then
-    LD_LIBRARY_PATH="" xmessage -nearmouse "${1}" 2>/dev/null
-  else
-    log "${1}"
-  fi
-  exit 1
-}
-
-yesno()
-{
-  TITLE=$1
-  TEXT=$2
-  if type yad >/dev/null 2>&1; then
-    LD_LIBRARY_PATH="" yad --borders=15 --center --on-top --width=400 --height=250 --button=gtk-no:1 --button=gtk-yes:0 --question --title="$TITLE" --text="$TEXT" 2>/dev/null && RETURN="yes" || RETURN="no"
-  elif type zenity >/dev/null 2>&1; then
-    LD_LIBRARY_PATH="" zenity --question --title="$TITLE" --text="$TEXT" 2>/dev/null && RETURN="yes" || RETURN="no"
-  elif type kdialog >/dev/null 2>&1; then
-    LD_LIBRARY_PATH="" kdialog --title "$TITLE" --yesno "$TEXT" && RETURN="yes" || RETURN="no"
-  elif type Xdialog >/dev/null 2>&1; then
-    LD_LIBRARY_PATH="" Xdialog --title "$TITLE" --clear --yesno "$TEXT" 10 80 && RETURN="yes" || RETURN="no"
-  elif type xmessage >/dev/null 2>&1; then
-    LD_LIBRARY_PATH="" xmessage -nearmouse -buttons No:1,Yes:0 "$TEXT" && RETURN="yes" || RETURN="no"
-  else
-    log "zenity, kdialog, Xdialog, xmessage missing. Skipping ${THIS}."
-    exit 0
-  fi
-}
-
 check_prevent()
 {
   FILE=$1
@@ -155,9 +133,10 @@ check_prevent()
 
 check_dep()
 {
-  if [ -z "$(command -v $1)" ]; then
-    log "$1 is missing. Skipping ${THIS}."
-    exit 
+  DEP=$1
+  if [ -z $(which $DEP) ] ; then
+    echo "$DEP is missing. Skipping ${THIS}."
+    exit 0
   fi
 }
 
@@ -211,7 +190,7 @@ check_prevent "/usr/share/$VENDORPREFIX/${APP}_no_desktopintegration"
 check_prevent "/etc/$VENDORPREFIX/${APP}_no_desktopintegration"
 
 if [ ! -f "$DESKTOPFILE" ] ; then
-  log "Desktop file is missing. Please run ${THIS} from within an AppImage."
+  echo "Desktop file is missing. Please run ${THIS} from within an AppImage."
   exit 0
 fi
 
@@ -235,15 +214,24 @@ fi
 
 # We ask the user only if we have found no reason to skip until here
 if [ -z "$SKIP" ] ; then
-  yesno "Install" "Would you like to integrate $APPIMAGE with your system?\n\nThis will add it to your applications menu and install icons.\nIf you don't do this you can still launch the application by double-clicking on the AppImage."
+  set +e
+  "$APPDIR/dialog" "AppImage - $APP_FULL"
+  RETURN=$?
+  set -e
 fi
 
-if [ "$RETURN" = "no" ] ; then
-  yesno "Disable question?" "Should this question be permanently disabled for $APP?\n\nTo re-enable this question you have to delete\n\"$STAMP_DIR/${APP}_no_desktopintegration\""
-  if [ "$RETURN" = "yes" ] ; then
-    mkdir -p "$STAMP_DIR"
-    touch "$STAMP_DIR/${APP}_no_desktopintegration"
-  fi
+RET_LAUNCH_APP=0       # launch app
+RET_MENU_ENTRY=1       # create desktop menu entry
+RET_DISABLE_MESSAGE=2  # disable the desktopintegration message
+RET_CLOSE_WINDOW=3     # window was closed with ALT+F4/ESC/X-button
+
+if [ $RETURN -eq $RET_DISABLE_MESSAGE ] ; then
+  mkdir -p "$STAMP_DIR"
+  touch "$STAMP_DIR/${APP}_no_desktopintegration"
+  exit 0
+elif [ $RETURN -eq $RET_MENU_ENTRY ] ; then
+  SKIP=
+else
   exit 0
 fi
 
@@ -257,7 +245,7 @@ if [ -z "$SKIP" ] ; then
   # For Exec we must use quotes
   # For TryExec quotes is not supported, so, space must be replaced to \s
   # https://askubuntu.com/questions/175404/how-to-add-space-to-exec-path-in-a-thumbnailer-descrption/175567
-  RESOURCE_NAME=$(echo "$VENDORPREFIX-$DESKTOPFILE_NAME" | sed -e 's/\.desktop//g')
+  RESOURCE_NAME=$(echo "$VENDORPREFIX-$DESKTOPFILE_NAME" | sed -e 's/.desktop//g')
   desktop-file-install --rebuild-mime-info-cache \
     --vendor=$VENDORPREFIX --set-key=Exec --set-value="\"${APPIMAGE}\" %U" \
     --set-key=X-AppImage-Comment --set-value="Generated by ${THIS}" \
